### ISSUE TITLE
Implementation Feature 2 - Week 14 - oeGetCrisisSet control and oeCloseCrisis reward function

### ISSUE THREAD

**Issue by Toppert93** [Toppert93/UL-IL-2017-g02#142]
Time allocated to Feature 2 on Implementation for Week 14.

**Comment by JVCruz1994** [comment]
closing a crisis now rewards coordinators with an extra experience point

**Comment by JVCruz1994** [comment]
coordinator is automatically promoted if the point he was rewarded reaches a new rank milestone

**Comment by JVCruz1994** [comment]
coordinators should now only see crisis that are at their level
