### ISSUE TITLE
Implementation Feature 2 - Week 15 - Demote coordinator and change crisis type buttons and implementation

### ISSUE THREAD

**Issue by Toppert93** [Toppert93/UL-IL-2017-g02#148]
Time allocated to Feature 2 on Implementation for Week 15.

**Comment by JVCruz1994** [comment]
fixed issue with the addCoordinator function

**Comment by JVCruz1994** [comment]
implementation of Demote coordinator button for the admin

**Comment by JVCruz1994** [comment]
implementation of Change crisis type button for coordinator
